steps:
  # Using a Node.js 20 image for yarn install and build
  - name: 'node:20-slim'
    entrypoint: 'yarn'
    args: ['install']
  - name: 'node:20-slim'
    entrypoint: 'yarn'
    args: ['build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
