steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']

  # Step 2: Build the React application
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'  # Adjust the timeout to your needs
